version: '3.7'

services:
  pathfinder:
    image: ${DOCKER_REGISTRY-}pathfinder
    build:
      context: .
      dockerfile: Pathfinder/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: ${SA_PWD}
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose: 
      - 1433